---
os: linux
dist: jammy

# jdk:
#   - openjdk11
#   - openjdk17

# language: scala
# scala:
#   - 2.12.18
#   - 2.13.11
#   - 3.3.0

# env:
#   matrix:
#     - TEST_COMMAND="compile Test/Compile"
#     - TEST_COMMAND="test"

before_cache: >-
  rm -fv $HOME/.ivy2/.sbt.ivy.lock \
  ; find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete \
  ; find $HOME/.sbt -name "*.lock" -print -delete

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.cache/coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_install: >-
  git fetch --tags

stages:
  - name: compile
  - name: test
  - name: release
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork

jobs:
  include:
    - stage: compile
      language: scala
      scala:
        - 2.12.18
        - 2.13.11
        - 3.3.0
      jdk:
        - openjdk11
        - openjdk17
      script: >-
        sbt compile Test/compile

    ################################################################################################

    - stage: test
      language: scala
      scala:
        - 2.12.18
        - 2.13.11
        - 3.3.0
      jdk:
        - openjdk11
        - openjdk17
      script: >-
        sbt test

    ################################################################################################

    - stage: release
      language: scala
      scala:
        - 2.12.18
        - 2.13.11
        - 3.3.0
      jdk:
        - openjdk11
        - openjdk17
      script: >-
        sbt +ci-release
