---
####################################################################################################
# templates
####################################################################################################

_compile: &compile
  language: scala
  scala:
    - OVERRIDE
  jdk:
    - OVERRIDE
  script: >-
    sbt ++$TRAVIS_SCALA_VERSION compile Test/compile

_test: &test
  language: scala
  scala:
    - OVERRIDE
  jdk:
    - OVERRIDE
  script: >-
    sbt ++$TRAVIS_SCALA_VERSION test

_release: &release
  language: scala
  scala:
    - OVERRIDE
  jdk:
    - openjdk11
  script: >-
    sbt ++$TRAVIS_SCALA_VERSION ci-release

####################################################################################################
# general
####################################################################################################

os: linux
dist: jammy

stages:
  - name: compile
  - name: test
  - name: release
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork

####################################################################################################
# jobs
####################################################################################################

jobs:
  include:

    ################################################################################################
    # compile
    ################################################################################################

    - stage: compile
      <<: *compile
      scala:
        - 2.12.18
      jdk:
        - openjdk11

    - stage: compile
      <<: *compile
      scala:
        - 2.12.18
      jdk:
        - openjdk17


    - stage: compile
      <<: *compile
      scala:
        - 2.13.11
      jdk:
        - openjdk11

    - stage: compile
      <<: *compile
      scala:
        - 2.13.11
      jdk:
        - openjdk17

    ## 3.3

    - stage: compile
      <<: *compile
      scala:
        - 3.3.0
      jdk:
        - openjdk11

    - stage: compile
      <<: *compile
      scala:
        - 3.3.0
      jdk:
        - openjdk17

    ################################################################################################
    # test
    ################################################################################################

    - stage: test
      <<: *test
      scala:
        - 2.12.18
      jdk:
        - openjdk11

    - stage: test
      <<: *test
      scala:
        - 2.12.18
      jdk:
        - openjdk17


    - stage: test
      <<: *test
      scala:
        - 2.13.11
      jdk:
        - openjdk11

    - stage: test
      <<: *test
      scala:
        - 2.13.11
      jdk:
        - openjdk17

    ## 3.3

    - stage: test
      <<: *test
      scala:
        - 3.3.0
      jdk:
        - openjdk11

    - stage: test
      <<: *test
      scala:
        - 3.3.0
      jdk:
        - openjdk17

    ################################################################################################
    # release
    ################################################################################################

    - stage: release
      <<: *release
      scala:
        - 2.12.18

    - stage: release
      <<: *release
      scala:
        - 2.13.11

    - stage: release
      <<: *release
      scala:
        - 3.3.0

####################################################################################################
# cache
####################################################################################################

before_cache: >-
  rm -fv $HOME/.ivy2/.sbt.ivy.lock \
  ; find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete \
  ; find $HOME/.sbt -name "*.lock" -print -delete

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.cache/coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt

####################################################################################################
# ci-release
####################################################################################################

before_install: >-
  git fetch --tags
