---
version: 2.1

####################################################################################################

executors:
  docker:
    resource_class: medium
    docker:
      - image: bdockerimg/sdkman:opensuse-tumbleweed
        environment:
          LANG: "en_US.UTF-8"
          JVM_OPTS: "-Xmx1024m"
          PGP_PASSPHRASE: "$PGP_PASSPHRASE"
          PGP_SECRET: "$PGP_SECRET"
          SONATYPE_PASSWORD: "$SONATYPE_PASSWORD"
          SONATYPE_USERNAME: "$SONATYPE_USERNAME"

####################################################################################################

jobs:
  build_test:
    executor: docker

    steps:
      - run:
          name: Install OpenJDK << parameters.openjdk_version >> and sbt
          shell: /bin/bash -l
          command: >-
            sdk list java
            | perl \
                -F '/\|/' -l \
                -E 'BEGIN { @vs=(); }' \
                -E 'push(@vs, $1)  if $F[5] =~ /\s*(<< parameters.openjdk_version >>.+-tem)/;' \
                -E 'END { sort @vs; say $vs[0]; }' > /tmp/java.version \
            && sdk install java $(</tmp/java.version)
            && sdk install sbt

      - checkout

      - restore_cache:
          name: Restore cache
          keys:
            - dependencies-{{ checksum "build.sbt" }}
            - dependencies-

      - run:
          name: Compile - OpenJDK << parameters.openjdk_version >>
          shell: "/bin/bash -l"
          command: >-
            sbt '+ compile ; Test/compile'

      - run:
          name: Clean the locks before saving the cache
          shell: "/bin/bash -l"
          command: >-
            find ~/.sbt -name "*.lock" -print -delete

      - save_cache:
          name: Save cache
          paths:
            - ~/.cache/coursier
            - ~/.sbt
          key: dependencies-{{ checksum "build.sbt" }}

      - run:
          name: Test - OpenJDK << parameters.openjdk_version >>
          shell: "/bin/bash -l"
          command: >-
            sbt '+ test'

      - store_test_results:
          path: target/test-reports

    working_directory: ~/persianutils

    parameters:
      openjdk_version:
        type: string

  ##################################################################################################

  release:
    executor: docker

    steps:
      - run:
          name: Install OpenJDK and sbt
          shell: "/bin/bash -l"
          command: >-
            sdk list java
            | perl \
                -F '/\|/' -l \
                -E 'BEGIN { @vs=(); }' \
                -E 'push(@vs, $1)  if $F[5] =~ /\s*(11.+-tem)/;' \
                -E 'END { sort @vs; say $vs[0]; }' > /tmp/java.version \
            && sdk install java $(</tmp/java.version)
            && sdk install sbt

      - checkout

      - run:
          name: Ensure tags are fetched
          shell: "/bin/bash -l"
          command: >-
            git fetch --tags

      - restore_cache:
          name: Restore cache
          keys:
            - dependencies-{{ checksum "build.sbt" }}
            - dependencies-

      - run:
          name: Release
          shell: "/bin/bash -l"
          command: >-
            sbt '+ ci-release'

    working_directory: ~/persianutils

####################################################################################################

workflows:
  build_test_release:
    jobs:
      - build_test:
          matrix:
            parameters:
              openjdk_version: ["11", "17"]
      - release:
          requires:
            - build_test
          filters:
            tags:
              only: /^v.+/
            branches:
              ignore: /.*/
