---
version: 2.1

####################################################################################################

executors:
  docker:
    docker:
      - image: opensuse/tumbleweed:latest
        environment:
          LANG: en_US.UTF-8
          JVM_OPTS: -Xmx1024m

####################################################################################################

jobs:
  build_test:
    executor: docker

    steps:
      - run:
          name: Install OpenJDK << matrix.openjdk_version >> and sbt
          command: >-
            curl -O --output-dir /etc/zypp/repos.d/ https://www.scala-sbt.org/sbt-rpm.repo
            && zypper --non-interactive refresh
            && zypper --non-interactive install java-<< matrix.openjdk_version >>-openjdk-devel sbt
            && { source /etc/profile || true; }

      - checkout

      - restore_cache:
          keys:
            - dependencies-{{ checksum "build.sbt" }}
            - dependencies-

      - run:
          name: Compile - Scala << matrix.scala_version >>  with OpenJDK << matrix.openjdk_version >>
          command: >-
            sbt ++<< matrix.scala_version >> compile Test/compile

      - save_cache:
          paths:
            - ~/.cache/coursier
            - ~/.sbt
          key: dependencies-{{ checksum "build.sbt" }}

      - run:
          name: Test - Scala << matrix.scala_version >>  with OpenJDK << matrix.openjdk_version >>
          command: >-
            sbt ++<< matrix.scala_version >> test

      - store_test_results:
          path: target/test-reports

    working_directory: ~/persianutils

    parameters:
      openjdk_version:
        type: string
      scala_version:
        type: string

####################################################################################################

workflows:
  build_test:
    jobs:
      - build_test:
          matrix:
            parameters:
              openjdk_version: ["11", "17"]
              scala_version: ["2.12.18", "2.13.12", "3.3.0"]
